# Generated by Django 2.0.1 on 2018-01-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frienderMain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pub_date',
            new_name='creationDate',
        ),
    ]
