# Generated by Django 2.0.1 on 2018-01-24 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frienderMain', '0002_auto_20180118_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailAddress',
            field=models.CharField(default='fakenewsemail@fakenews.com', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='facebookProfileURL',
            field=models.TextField(default='https://www.facebook.com/', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='user',
            name='twitterProfileURL',
            field=models.TextField(default='https://www.twitter.com/', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='test', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
